### PR TITLE
Default %_lto_cflags to -flto=auto.

### PR DESCRIPTION
**Pull request by marxin**
@mlschroe

### CODE REVIEW

**Comment by mlschroe** [comment]
And:

```
Since -flto can be overridden with
by simply appending -fno-lto for the packages that need to disable it,
there's no practical need for us to provide such a macro for disabling
either.
```

**Comment by marxin** [comment]
> Either rpm upstream is wrong or this is not needed. Citing Panu:
> 
> ```
>     In addition, gcc upstream has decided to make -flto default to autodetected parallelism.
> ```

Yes, but it will be true starting from new GCC release 10.1.
Right now, as we're using `GCC 9.2` we need the option.
But yes, for the future we should use directly `-flto` in `$Optflags` and disable it per package with `-fno-lto`.

**Comment by marxin** [comment]
I was not clear enough. The macro will not be needed as soon as we change all packages that use modifications of `%_lto_cflags` to either disable LTO, or to use FAT LTO object files.

**Comment by marxin** [comment]
@mlschroe ping

**Comment by mlschroe** [comment]
ok, added.

**Pull request closed without merging**
